apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 324037301009.dkr.ecr.ap-southeast-1.amazonaws.com/charanecr:github.sha
        ports:
        - containerPort: 8080
